In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
import re

In [2]:
df = pd.read_csv('eazydiner_dataset.csv')

In [3]:
df

,Restaurant_Name,Rating,Area,Dishes,Amount,Discount
0,Brot Company,5.0,"Civil Lines, Jaipur","Bakery, Pan Asian, Continental",₹ 1600 for two approx.,20% Off + 25% Off
1,Govindam Retreat,4.4,"Kanwar Nagar, Jaipur",Multicuisine,₹ 700 for two approx.,25% Off
2,Spice Court,4.4,"Civil Lines, Jaipur","Multicuisine, Beverages",₹ 800 for two approx.,10% Off + 25% Off
3,Cafe Auberge,4.8,"Civil Lines, Jaipur",Multicuisine,₹ 800 for two approx.,20% Off + 25% Off
4,Dyore Experiences,3.3,"C Scheme, Jaipur",Multicuisine,₹ 1800 for two approx.,20% Off + 25% Off
...,...,...,...,...,...,...
670,Kenzai - Asian Kitchen And Lounge,4.6,"Brigade Road, Central Bengaluru",Asian,₹ 2000 for two approx.,25% Off + 25% Off
671,Cahoots Classic Bar House,5.0,"Brigade Road, Central Bengaluru",Multicuisine,₹ 4000 for two approx.,10% Off + 25% Off
672,i-Bar,3.8,"The Park, Bengaluru",Cocktail Menu,₹ 2000 for two approx.,30% Off + 25% Off
673,Sea Rock Family Restaurant & Bar,4.7,"Seshadripuram, Central Bengaluru",Multicuisine,₹ 2000 for two approx.,10% Off + 25% Off
674,Badmaash UB City,4.3,"UB City, Central Bengaluru | View All(4) Outlets",Indian,₹ 2000 for two approx.,25% Off + 25% Off

In [4]:
df['Area'] = df['Area'].str.replace('\xa0 \| View All\(\d+\) Outlets', '', regex=True)

In [5]:
df

,Restaurant_Name,Rating,Area,Dishes,Amount,Discount
0,Brot Company,5.0,"Civil Lines, Jaipur","Bakery, Pan Asian, Continental",₹ 1600 for two approx.,20% Off + 25% Off
1,Govindam Retreat,4.4,"Kanwar Nagar, Jaipur",Multicuisine,₹ 700 for two approx.,25% Off
2,Spice Court,4.4,"Civil Lines, Jaipur","Multicuisine, Beverages",₹ 800 for two approx.,10% Off + 25% Off
3,Cafe Auberge,4.8,"Civil Lines, Jaipur",Multicuisine,₹ 800 for two approx.,20% Off + 25% Off
4,Dyore Experiences,3.3,"C Scheme, Jaipur",Multicuisine,₹ 1800 for two approx.,20% Off + 25% Off
...,...,...,...,...,...,...
670,Kenzai - Asian Kitchen And Lounge,4.6,"Brigade Road, Central Bengaluru",Asian,₹ 2000 for two approx.,25% Off + 25% Off
671,Cahoots Classic Bar House,5.0,"Brigade Road, Central Bengaluru",Multicuisine,₹ 4000 for two approx.,10% Off + 25% Off
672,i-Bar,3.8,"The Park, Bengaluru",Cocktail Menu,₹ 2000 for two approx.,30% Off + 25% Off
673,Sea Rock Family Restaurant & Bar,4.7,"Seshadripuram, Central Bengaluru",Multicuisine,₹ 2000 for two approx.,10% Off + 25% Off
674,Badmaash UB City,4.3,"UB City, Central Bengaluru",Indian,₹ 2000 for two approx.,25% Off + 25% Off

In [6]:
# Remove everything after the first comma in 'Area'
df['Area'] = df['Area'].str.split(',', n=1).str[0]

In [7]:
df

,Restaurant_Name,Rating,Area,Dishes,Amount,Discount
0,Brot Company,5.0,Civil Lines,"Bakery, Pan Asian, Continental",₹ 1600 for two approx.,20% Off + 25% Off
1,Govindam Retreat,4.4,Kanwar Nagar,Multicuisine,₹ 700 for two approx.,25% Off
2,Spice Court,4.4,Civil Lines,"Multicuisine, Beverages",₹ 800 for two approx.,10% Off + 25% Off
3,Cafe Auberge,4.8,Civil Lines,Multicuisine,₹ 800 for two approx.,20% Off + 25% Off
4,Dyore Experiences,3.3,C Scheme,Multicuisine,₹ 1800 for two approx.,20% Off + 25% Off
...,...,...,...,...,...,...
670,Kenzai - Asian Kitchen And Lounge,4.6,Brigade Road,Asian,₹ 2000 for two approx.,25% Off + 25% Off
671,Cahoots Classic Bar House,5.0,Brigade Road,Multicuisine,₹ 4000 for two approx.,10% Off + 25% Off
672,i-Bar,3.8,The Park,Cocktail Menu,₹ 2000 for two approx.,30% Off + 25% Off
673,Sea Rock Family Restaurant & Bar,4.7,Seshadripuram,Multicuisine,₹ 2000 for two approx.,10% Off + 25% Off
674,Badmaash UB City,4.3,UB City,Indian,₹ 2000 for two approx.,25% Off + 25% Off

In [8]:
df['Amount'] = df['Amount'].str.replace('\D', '', regex=True)

In [9]:
df

,Restaurant_Name,Rating,Area,Dishes,Amount,Discount
0,Brot Company,5.0,Civil Lines,"Bakery, Pan Asian, Continental",1600,20% Off + 25% Off
1,Govindam Retreat,4.4,Kanwar Nagar,Multicuisine,700,25% Off
2,Spice Court,4.4,Civil Lines,"Multicuisine, Beverages",800,10% Off + 25% Off
3,Cafe Auberge,4.8,Civil Lines,Multicuisine,800,20% Off + 25% Off
4,Dyore Experiences,3.3,C Scheme,Multicuisine,1800,20% Off + 25% Off
...,...,...,...,...,...,...
670,Kenzai - Asian Kitchen And Lounge,4.6,Brigade Road,Asian,2000,25% Off + 25% Off
671,Cahoots Classic Bar House,5.0,Brigade Road,Multicuisine,4000,10% Off + 25% Off
672,i-Bar,3.8,The Park,Cocktail Menu,2000,30% Off + 25% Off
673,Sea Rock Family Restaurant & Bar,4.7,Seshadripuram,Multicuisine,2000,10% Off + 25% Off
674,Badmaash UB City,4.3,UB City,Indian,2000,25% Off + 25% Off

In [10]:
locations = ['jaipur', 'goa', 'patna', 'mumbai', 'bengaluru']
loc = np.repeat(locations, 135)
df['Location'] = loc

In [11]:
df

,Restaurant_Name,Rating,Area,Dishes,Amount,Discount,Location
0,Brot Company,5.0,Civil Lines,"Bakery, Pan Asian, Continental",1600,20% Off + 25% Off,jaipur
1,Govindam Retreat,4.4,Kanwar Nagar,Multicuisine,700,25% Off,jaipur
2,Spice Court,4.4,Civil Lines,"Multicuisine, Beverages",800,10% Off + 25% Off,jaipur
3,Cafe Auberge,4.8,Civil Lines,Multicuisine,800,20% Off + 25% Off,jaipur
4,Dyore Experiences,3.3,C Scheme,Multicuisine,1800,20% Off + 25% Off,jaipur
...,...,...,...,...,...,...,...
670,Kenzai - Asian Kitchen And Lounge,4.6,Brigade Road,Asian,2000,25% Off + 25% Off,bengaluru
671,Cahoots Classic Bar House,5.0,Brigade Road,Multicuisine,4000,10% Off + 25% Off,bengaluru
672,i-Bar,3.8,The Park,Cocktail Menu,2000,30% Off + 25% Off,bengaluru
673,Sea Rock Family Restaurant & Bar,4.7,Seshadripuram,Multicuisine,2000,10% Off + 25% Off,bengaluru
674,Badmaash UB City,4.3,UB City,Indian,2000,25% Off + 25% Off,bengaluru

In [12]:
Restaurant_Discount = []
for i in df['Discount']:
    if '+' in i:
        d = i.split('+')[0]
        Restaurant_Discount.append(d)
    else:
        Restaurant_Discount.append(np.nan)
df['Restaurant_Discount'] = Restaurant_Discount

Restaurant_Discount = []
for i in df['Restaurant_Discount']:
    if isinstance(i, str) and 'Off' in i:
        d = re.sub('\D', '', i)
        Restaurant_Discount.append(d)
    else:
        Restaurant_Discount.append(np.nan)
df['Restaurant_Discount'] = Restaurant_Discount

In [13]:
df

,Restaurant_Name,Rating,Area,Dishes,Amount,Discount,Location,Restaurant_Discount
0,Brot Company,5.0,Civil Lines,"Bakery, Pan Asian, Continental",1600,20% Off + 25% Off,jaipur,20
1,Govindam Retreat,4.4,Kanwar Nagar,Multicuisine,700,25% Off,jaipur,NaN
2,Spice Court,4.4,Civil Lines,"Multicuisine, Beverages",800,10% Off + 25% Off,jaipur,10
3,Cafe Auberge,4.8,Civil Lines,Multicuisine,800,20% Off + 25% Off,jaipur,20
4,Dyore Experiences,3.3,C Scheme,Multicuisine,1800,20% Off + 25% Off,jaipur,20
...,...,...,...,...,...,...,...,...
670,Kenzai - Asian Kitchen And Lounge,4.6,Brigade Road,Asian,2000,25% Off + 25% Off,bengaluru,25
671,Cahoots Classic Bar House,5.0,Brigade Road,Multicuisine,4000,10% Off + 25% Off,bengaluru,10
672,i-Bar,3.8,The Park,Cocktail Menu,2000,30% Off + 25% Off,bengaluru,30
673,Sea Rock Family Restaurant & Bar,4.7,Seshadripuram,Multicuisine,2000,10% Off + 25% Off,bengaluru,10
674,Badmaash UB City,4.3,UB City,Indian,2000,25% Off + 25% Off,bengaluru,25

In [14]:
Payment_Discount = []
for i in df['Discount']:
    if '+' in i:
        d = i.split('+')[1]
        Payment_Discount.append(d)
    else:
        Payment_Discount.append(np.nan)
df['Payment_Discount'] = Payment_Discount

Payment_Discount = []
for i in df['Payment_Discount']:
    if isinstance(i, str) and 'Off' in i:
        d = re.sub('\D', '', i)
        Payment_Discount.append(d)
    else:
        Payment_Discount.append(np.nan)
df['Payment_Discount'] = Payment_Discount

In [15]:
df

,Restaurant_Name,Rating,Area,Dishes,Amount,Discount,Location,Restaurant_Discount,Payment_Discount
0,Brot Company,5.0,Civil Lines,"Bakery, Pan Asian, Continental",1600,20% Off + 25% Off,jaipur,20,25
1,Govindam Retreat,4.4,Kanwar Nagar,Multicuisine,700,25% Off,jaipur,NaN,NaN
2,Spice Court,4.4,Civil Lines,"Multicuisine, Beverages",800,10% Off + 25% Off,jaipur,10,25
3,Cafe Auberge,4.8,Civil Lines,Multicuisine,800,20% Off + 25% Off,jaipur,20,25
4,Dyore Experiences,3.3,C Scheme,Multicuisine,1800,20% Off + 25% Off,jaipur,20,25
...,...,...,...,...,...,...,...,...,...
670,Kenzai - Asian Kitchen And Lounge,4.6,Brigade Road,Asian,2000,25% Off + 25% Off,bengaluru,25,25
671,Cahoots Classic Bar House,5.0,Brigade Road,Multicuisine,4000,10% Off + 25% Off,bengaluru,10,25
672,i-Bar,3.8,The Park,Cocktail Menu,2000,30% Off + 25% Off,bengaluru,30,25
673,Sea Rock Family Restaurant & Bar,4.7,Seshadripuram,Multicuisine,2000,10% Off + 25% Off,bengaluru,10,25
674,Badmaash UB City,4.3,UB City,Indian,2000,25% Off + 25% Off,bengaluru,25,25

In [16]:
df = df.drop(columns=['Discount'])

In [17]:
df

,Restaurant_Name,Rating,Area,Dishes,Amount,Location,Restaurant_Discount,Payment_Discount
0,Brot Company,5.0,Civil Lines,"Bakery, Pan Asian, Continental",1600,jaipur,20,25
1,Govindam Retreat,4.4,Kanwar Nagar,Multicuisine,700,jaipur,NaN,NaN
2,Spice Court,4.4,Civil Lines,"Multicuisine, Beverages",800,jaipur,10,25
3,Cafe Auberge,4.8,Civil Lines,Multicuisine,800,jaipur,20,25
4,Dyore Experiences,3.3,C Scheme,Multicuisine,1800,jaipur,20,25
...,...,...,...,...,...,...,...,...
670,Kenzai - Asian Kitchen And Lounge,4.6,Brigade Road,Asian,2000,bengaluru,25,25
671,Cahoots Classic Bar House,5.0,Brigade Road,Multicuisine,4000,bengaluru,10,25
672,i-Bar,3.8,The Park,Cocktail Menu,2000,bengaluru,30,25
673,Sea Rock Family Restaurant & Bar,4.7,Seshadripuram,Multicuisine,2000,bengaluru,10,25
674,Badmaash UB City,4.3,UB City,Indian,2000,bengaluru,25,25

In [18]:
df['Restaurant_Discount'] = df['Restaurant_Discount'].fillna(0)
df['Payment_Discount'] = df['Payment_Discount'].fillna(0)

In [19]:
df

,Restaurant_Name,Rating,Area,Dishes,Amount,Location,Restaurant_Discount,Payment_Discount
0,Brot Company,5.0,Civil Lines,"Bakery, Pan Asian, Continental",1600,jaipur,20,25
1,Govindam Retreat,4.4,Kanwar Nagar,Multicuisine,700,jaipur,0,0
2,Spice Court,4.4,Civil Lines,"Multicuisine, Beverages",800,jaipur,10,25
3,Cafe Auberge,4.8,Civil Lines,Multicuisine,800,jaipur,20,25
4,Dyore Experiences,3.3,C Scheme,Multicuisine,1800,jaipur,20,25
...,...,...,...,...,...,...,...,...
670,Kenzai - Asian Kitchen And Lounge,4.6,Brigade Road,Asian,2000,bengaluru,25,25
671,Cahoots Classic Bar House,5.0,Brigade Road,Multicuisine,4000,bengaluru,10,25
672,i-Bar,3.8,The Park,Cocktail Menu,2000,bengaluru,30,25
673,Sea Rock Family Restaurant & Bar,4.7,Seshadripuram,Multicuisine,2000,bengaluru,10,25
674,Badmaash UB City,4.3,UB City,Indian,2000,bengaluru,25,25

In [20]:
# Convert to string first, remove non-numeric characters, then to int
df['Amount'] = df['Amount'].astype(str).str.replace(r'[^0-9]', '', regex=True).astype(int)
df['Restaurant_Discount'] = pd.to_numeric(df['Restaurant_Discount'].astype(str).str.replace(r'[^0-9]', '', regex=True), errors='coerce').fillna(0).astype(int)
df['Payment_Discount'] = pd.to_numeric(df['Payment_Discount'].astype(str).str.replace(r'[^0-9]', '', regex=True), errors='coerce').fillna(0).astype(int)

In [21]:
df

,Restaurant_Name,Rating,Area,Dishes,Amount,Location,Restaurant_Discount,Payment_Discount
0,Brot Company,5.0,Civil Lines,"Bakery, Pan Asian, Continental",1600,jaipur,20,25
1,Govindam Retreat,4.4,Kanwar Nagar,Multicuisine,700,jaipur,0,0
2,Spice Court,4.4,Civil Lines,"Multicuisine, Beverages",800,jaipur,10,25
3,Cafe Auberge,4.8,Civil Lines,Multicuisine,800,jaipur,20,25
4,Dyore Experiences,3.3,C Scheme,Multicuisine,1800,jaipur,20,25
...,...,...,...,...,...,...,...,...
670,Kenzai - Asian Kitchen And Lounge,4.6,Brigade Road,Asian,2000,bengaluru,25,25
671,Cahoots Classic Bar House,5.0,Brigade Road,Multicuisine,4000,bengaluru,10,25
672,i-Bar,3.8,The Park,Cocktail Menu,2000,bengaluru,30,25
673,Sea Rock Family Restaurant & Bar,4.7,Seshadripuram,Multicuisine,2000,bengaluru,10,25
674,Badmaash UB City,4.3,UB City,Indian,2000,bengaluru,25,25

In [22]:
df['discount_value'] = (df['Restaurant_Discount'] + df['Payment_Discount'])/100 * df['Amount']
df['final_bill'] = df['Amount'] - df['discount_value']

df['discount_value'] = df['discount_value'].map('{:.2f}'.format)
df['final_bill'] = df['final_bill'].map('{:.2f}'.format)

In [23]:
df

,Restaurant_Name,Rating,Area,Dishes,Amount,Location,Restaurant_Discount,Payment_Discount,discount_value,final_bill
0,Brot Company,5.0,Civil Lines,"Bakery, Pan Asian, Continental",1600,jaipur,20,25,720.00,880.00
1,Govindam Retreat,4.4,Kanwar Nagar,Multicuisine,700,jaipur,0,0,0.00,700.00
2,Spice Court,4.4,Civil Lines,"Multicuisine, Beverages",800,jaipur,10,25,280.00,520.00
3,Cafe Auberge,4.8,Civil Lines,Multicuisine,800,jaipur,20,25,360.00,440.00
4,Dyore Experiences,3.3,C Scheme,Multicuisine,1800,jaipur,20,25,810.00,990.00
...,...,...,...,...,...,...,...,...,...,...
670,Kenzai - Asian Kitchen And Lounge,4.6,Brigade Road,Asian,2000,bengaluru,25,25,1000.00,1000.00
671,Cahoots Classic Bar House,5.0,Brigade Road,Multicuisine,4000,bengaluru,10,25,1400.00,2600.00
672,i-Bar,3.8,The Park,Cocktail Menu,2000,bengaluru,30,25,1100.00,900.00
673,Sea Rock Family Restaurant & Bar,4.7,Seshadripuram,Multicuisine,2000,bengaluru,10,25,700.00,1300.00
674,Badmaash UB City,4.3,UB City,Indian,2000,bengaluru,25,25,1000.00,1000.00

In [24]:
df['Restaurant_Discount'].unique()

array([20,  0, 10, 15, 30, 25, 40, 45, 55, 35, 50])

In [25]:
df['Payment_Discount'].unique()

array([25,  0])

In [26]:
df = df.drop(columns=['Payment_Discount'])

In [27]:
df

,Restaurant_Name,Rating,Area,Dishes,Amount,Location,Restaurant_Discount,discount_value,final_bill
0,Brot Company,5.0,Civil Lines,"Bakery, Pan Asian, Continental",1600,jaipur,20,720.00,880.00
1,Govindam Retreat,4.4,Kanwar Nagar,Multicuisine,700,jaipur,0,0.00,700.00
2,Spice Court,4.4,Civil Lines,"Multicuisine, Beverages",800,jaipur,10,280.00,520.00
3,Cafe Auberge,4.8,Civil Lines,Multicuisine,800,jaipur,20,360.00,440.00
4,Dyore Experiences,3.3,C Scheme,Multicuisine,1800,jaipur,20,810.00,990.00
...,...,...,...,...,...,...,...,...,...
670,Kenzai - Asian Kitchen And Lounge,4.6,Brigade Road,Asian,2000,bengaluru,25,1000.00,1000.00
671,Cahoots Classic Bar House,5.0,Brigade Road,Multicuisine,4000,bengaluru,10,1400.00,2600.00
672,i-Bar,3.8,The Park,Cocktail Menu,2000,bengaluru,30,1100.00,900.00
673,Sea Rock Family Restaurant & Bar,4.7,Seshadripuram,Multicuisine,2000,bengaluru,10,700.00,1300.00
674,Badmaash UB City,4.3,UB City,Indian,2000,bengaluru,25,1000.00,1000.00

In [28]:
df.duplicated().sum()

np.int64(0)

In [29]:
df.isnull().sum()

Restaurant_Name        0
Rating                 0
Area                   0
Dishes                 0
Amount                 0
Location               0
Restaurant_Discount    0
discount_value         0
final_bill             0
dtype: int64

In [30]:
df.describe()

           Rating       Amount  Restaurant_Discount
count  675.000000   675.000000           675.000000
mean     4.286963  1520.288889            17.414815
std      0.570082   823.263543            13.843329
min      1.000000   300.000000             0.000000
25%      4.000000  1000.000000            10.000000
50%      4.300000  1400.000000            15.000000
75%      4.600000  2000.000000            25.000000
max      5.000000  6000.000000            55.000000

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 675 entries, 0 to 674
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Restaurant_Name      675 non-null    object
 1   Rating               675 non-null    float64
 2   Area                 675 non-null    object
 3   Dishes               675 non-null    object
 4   Amount               675 non-null    int64
 5   Location             675 non-null    object
 6   Restaurant_Discount  675 non-null    int64
 7   discount_value       675 non-null    object
 8   final_bill           675 non-null    object
dtypes: float64(1), int64(2), object(6)
memory usage: 47.6+ KB

In [32]:
df.to_csv('eazydiner_cleandata.csv', index=False)

In [33]:
df

,Restaurant_Name,Rating,Area,Dishes,Amount,Location,Restaurant_Discount,discount_value,final_bill
0,Brot Company,5.0,Civil Lines,"Bakery, Pan Asian, Continental",1600,jaipur,20,720.00,880.00
1,Govindam Retreat,4.4,Kanwar Nagar,Multicuisine,700,jaipur,0,0.00,700.00
2,Spice Court,4.4,Civil Lines,"Multicuisine, Beverages",800,jaipur,10,280.00,520.00
3,Cafe Auberge,4.8,Civil Lines,Multicuisine,800,jaipur,20,360.00,440.00
4,Dyore Experiences,3.3,C Scheme,Multicuisine,1800,jaipur,20,810.00,990.00
...,...,...,...,...,...,...,...,...,...
670,Kenzai - Asian Kitchen And Lounge,4.6,Brigade Road,Asian,2000,bengaluru,25,1000.00,1000.00
671,Cahoots Classic Bar House,5.0,Brigade Road,Multicuisine,4000,bengaluru,10,1400.00,2600.00
672,i-Bar,3.8,The Park,Cocktail Menu,2000,bengaluru,30,1100.00,900.00
673,Sea Rock Family Restaurant & Bar,4.7,Seshadripuram,Multicuisine,2000,bengaluru,10,700.00,1300.00
674,Badmaash UB City,4.3,UB City,Indian,2000,bengaluru,25,1000.00,1000.00